# Generated by Django 3.0.8 on 2020-07-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('budget_price', models.IntegerField(blank=True, null=True)),
                ('last_price', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(max_length=200)),
                ('discount_price', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='items',
        ),
    ]
